# Generated by Django 3.1.7 on 2021-03-15 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
                ('datetime', models.DateField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('code', models.TextField()),
            ],
        ),
    ]
